/* Fase 11: métricas manuales, análisis descriptivo y registro de aprendizaje. */
(() => {
  "use strict";
  const $ = (s, r=document) => r.querySelector(s);
  const metrics = [{key:"reach",label:"Alcance"},{key:"impressions",label:"Impresiones"},{key:"engagements",label:"Interacciones"},{key:"clicks",label:"Clics"},{key:"conversions",label:"Conversiones"}];
  const esc = (value) => String(value ?? "");
  function node(tag, cls, text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el;}
  async function getData(){const r=await window.AppStorage.read();if(r.warning)throw new Error(r.warning);return r.data||{};}
  async function saveData(d){const r=await window.AppStorage.write(d);if(!r.ok)throw new Error(r.error||"No se pudieron guardar los datos.");window.dispatchEvent(new CustomEvent("content-commander:analytics-updated"));}
  function numericValue(input){if(input.value.trim()==="")return null;const n=Number(input.value);if(!Number.isFinite(n)||n<0||!Number.isInteger(n))throw new Error("Las métricas deben ser enteros iguales o mayores que cero. Deja en blanco lo que no tengas disponible.");return n;}
  function format(n){return new Intl.NumberFormat("es-MX",{maximumFractionDigits:1}).format(n);}
  function avg(records,key){const vals=records.map(r=>r[key]).filter(v=>Number.isFinite(v));return vals.length?{value:vals.reduce((a,b)=>a+b,0)/vals.length,n:vals.length}:null;}
  function fillLinkedRecords(records){const select=$("#learning-note-record");const chosen=select.value;select.replaceChildren();select.append(new Option("Sin publicación vinculada",""));records.forEach(r=>select.append(new Option(r.title,r.id)));if(records.some(r=>r.id===chosen))select.value=chosen;}
  function renderInsights(records){const wrap=$("#analytics-insights");wrap.replaceChildren();if(records.length<2){wrap.append(node("p","helper","Registra al menos dos publicaciones para comparar promedios descriptivos. Evita concluir que una diferencia se debe al formato sin controlar objetivo, audiencia, periodo y distribución."));return;}
    const groups=new Map();records.forEach(r=>{const key=`${r.format||"Sin formato"} · ${r.goal||"Sin objetivo"}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);});
    const cards=[];for(const [key,items] of groups){if(items.length<2)continue;const lines=metrics.map(m=>{const a=avg(items,m.key);return a?`${m.label}: promedio ${format(a.value)} (${a.n} con dato)`:null;}).filter(Boolean);if(lines.length)cards.push({key,count:items.length,lines});}
    if(!cards.length){wrap.append(node("p","helper","Aún no hay grupos comparables con al menos dos piezas del mismo formato y objetivo. Puedes seguir registrando resultados; no se inventan comparaciones."));return;}
    cards.forEach(c=>{const card=node("article","analytics-insight");card.append(node("h4", "", c.key));card.append(node("p","analytics-meta",`${c.count} publicaciones registradas`));const ul=node("ul");c.lines.forEach(line=>ul.append(node("li","",line)));card.append(ul);card.append(node("p","helper","Promedios descriptivos; no demuestran causalidad ni representan un benchmark de mercado."));wrap.append(card);});
  }
  function render(){getData().then(d=>{const all=Array.isArray(d.analyticsRecords)?d.analyticsRecords:[];const filter=$("#analytics-filter").value;const records=filter==="all"?all:all.filter(r=>r.network===filter);const summary=$("#analytics-summary");summary.replaceChildren();summary.append(node("b","",`${records.length} publicación(es) en esta vista`));const grid=node("div","analytics-metric-grid");metrics.forEach(m=>{const a=avg(records,m.key);const card=node("div","analytics-mini-metric");card.append(node("span","",m.label),node("strong","",a?format(a.value):"—"),node("small","",a?`Promedio de ${a.n} registro(s) con dato`:`Sin datos disponibles`));grid.append(card);});summary.append(grid);renderInsights(records);
      const wrap=$("#analytics-records");wrap.replaceChildren();if(!records.length)wrap.append(node("p","helper","No hay resultados para este filtro. Registra métricas reales; los campos vacíos no se interpretan como cero."));records.slice().sort((a,b)=>(b.date||b.createdAt||"").localeCompare(a.date||a.createdAt||"")).forEach(r=>{const card=node("article","analytics-record");card.append(node("h4","",r.title));card.append(node("p","analytics-meta",`${r.date||"Fecha no indicada"} · ${r.network} · ${r.format} · ${r.goal} · ${r.pillar||"Sin pilar"}`));const values=metrics.map(m=>`${m.label}: ${r[m.key]===null||r[m.key]===undefined?"No disponible":format(r[m.key])}`).join(" · ");card.append(node("p","analytics-values",values));if(r.notes)card.append(node("p","analytics-values",`Notas: ${r.notes}`));const del=node("button","button button-secondary analytics-delete","Eliminar registro");del.type="button";del.addEventListener("click",async()=>{if(!confirm("¿Eliminar este registro de métricas? Los aprendizajes vinculados se conservarán como notas históricas."))return;const data=await getData();data.analyticsRecords=(data.analyticsRecords||[]).filter(x=>x.id!==r.id);await saveData(data);render();});card.append(del);wrap.append(card);});fillLinkedRecords(all);
      const notesWrap=$("#analytics-learning-notes");notesWrap.replaceChildren();const notes=Array.isArray(d.editorialLearnings)?d.editorialLearnings:[];if(!notes.length)notesWrap.append(node("p","helper","Todavía no hay aprendizajes registrados."));notes.slice().reverse().forEach(n=>{const card=node("article","analytics-record");card.append(node("h4","",({observation:"Observación",hypothesis:"Hipótesis por validar",experiment:"Próximo experimento",decision:"Decisión editorial"})[n.type]||"Aprendizaje"));card.append(node("p","analytics-values",n.text));if(n.nextStep)card.append(node("p","analytics-meta",`Validación / siguiente paso: ${n.nextStep}`));card.append(node("p","analytics-meta",`${n.recordTitle?`Publicación: ${n.recordTitle} · `:""}${new Date(n.createdAt).toLocaleDateString("es-MX")}`));const del=node("button","button button-secondary analytics-delete","Eliminar aprendizaje");del.type="button";del.addEventListener("click",async()=>{const data=await getData();data.editorialLearnings=(data.editorialLearnings||[]).filter(x=>x.id!==n.id);await saveData(data);render();});card.append(del);notesWrap.append(card);});
    }).catch(e=>{$("#analytics-feedback").textContent=e.message;});}
  function id(){return globalThis.crypto?.randomUUID?crypto.randomUUID():`an-${Date.now()}-${Math.random().toString(16).slice(2)}`;}
  function init(){
    $("#analytics-form").addEventListener("submit",async e=>{e.preventDefault();const feedback=$("#analytics-feedback");try{const record={id:id(),title:$("#an-title").value.trim(),date:$("#an-date").value||"",network:$("#an-network").value,format:$("#an-format").value,goal:$("#an-goal").value,pillar:$("#an-pillar").value.trim(),notes:$("#an-notes").value.trim(),createdAt:new Date().toISOString()};if(!record.title)throw new Error("Escribe el título de la publicación.");metrics.forEach(m=>record[m.key]=numericValue($("#an-"+m.key)));const d=await getData();d.analyticsRecords=Array.isArray(d.analyticsRecords)?d.analyticsRecords:[];d.analyticsRecords.push(record);await saveData(d);e.target.reset();feedback.textContent="Resultados guardados. Los valores vacíos se conservaron como no disponibles.";feedback.dataset.state="success";render();}catch(err){feedback.textContent=err.message;feedback.dataset.state="error";}});
    $("#learning-note-form").addEventListener("submit",async e=>{e.preventDefault();const feedback=$("#learning-note-feedback");try{const textVal=$("#learning-note-text").value.trim();if(!textVal)throw new Error("Escribe el aprendizaje o la hipótesis.");const d=await getData();d.editorialLearnings=Array.isArray(d.editorialLearnings)?d.editorialLearnings:[];const record=(d.analyticsRecords||[]).find(r=>r.id===$("#learning-note-record").value);d.editorialLearnings.push({id:id(),recordId:record?.id||"",recordTitle:record?.title||"",type:$("#learning-note-type").value,text:textVal,nextStep:$("#learning-note-next").value.trim(),createdAt:new Date().toISOString()});await saveData(d);e.target.reset();feedback.textContent="Aprendizaje guardado. Las hipótesis siguen marcadas como pendientes de validar.";feedback.dataset.state="success";render();}catch(err){feedback.textContent=err.message;feedback.dataset.state="error";}});
    $("#analytics-filter").addEventListener("change",render);window.addEventListener("content-commander:route-changed",e=>{if(e.detail?.view==="analitica")render();});window.addEventListener("content-commander:analytics-updated",()=>{});render();
  }
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
  window.AppAnalytics={refresh:render};
})();
