/* Asistente pedagógico: propuestas explícitas, sin guardar ni sobrescribir datos automáticamente. */
(() => {
  "use strict";
  const $ = s => document.querySelector(s);
  const readData = async () => { const r = await window.AppStorage.read(); if (r.warning) throw new Error(r.warning); return r.data || {}; };
  const show = (root, text) => { root.replaceChildren(); const pre = document.createElement("pre"); pre.className = "ai-coach-text"; pre.textContent = text; root.append(pre); const copy = document.createElement("button"); copy.type = "button"; copy.className = "button button-secondary"; copy.textContent = "Copiar propuesta"; copy.addEventListener("click", async () => { try { await navigator.clipboard.writeText(text); copy.textContent = "Copiado"; } catch (_) { copy.textContent = "Selecciona y copia el texto"; } }); root.append(copy); root.hidden = false; };
  async function run(buttonId, statusId, resultId, buildPrompt, maxTokens=1300) {
    const button=$(buttonId), status=$(statusId), result=$(resultId); if (!button || !status || !result) return;
    button.disabled=true; const original=button.textContent; button.textContent="Preparando recomendación…"; status.textContent="La IA está analizando la información disponible. Puede tardar unos segundos."; result.hidden=true;
    try { const data=await readData(); if (!window.AppCohere) throw new Error("El módulo de Cohere no está disponible. Recarga la aplicación."); const response=await window.AppCohere.chat([{role:"user",content:buildPrompt(data)}],{maxTokens,temperature:0.25}); show(result,response.text); status.textContent=`Propuesta recibida de ${response.model}. No se ha guardado ni aplicado ningún cambio; revisa y copia lo que te sirva.`; }
    catch(e) { status.textContent=e.message || "No se pudo obtener la propuesta."; status.dataset.state="error"; }
    finally { button.disabled=false; button.textContent=original; }
  }
  const rules = `Responde en español claro para una persona principiante. Explica con palabras sencillas y evita jerga sin definirla. No inventes hechos de empresa, clientes, pruebas, estadísticas ni resultados. Separa claramente: (1) lo que sabemos por los datos aportados, (2) propuestas/hipótesis de trabajo, (3) preguntas concretas que la persona puede responder y (4) qué debe validar antes de aprobar. Si falta información, dilo explícitamente y usa [POR VALIDAR]. No afirmes que una propuesta es un hecho comprobado. Da recomendaciones concretas, accionables y adaptadas al contexto disponible, no una plantilla genérica.`;
  $("#coach-company")?.addEventListener("click", () => run("#coach-company","#coach-company-status","#coach-company-result", data => `${rules}\n\nACTÚA COMO CONSULTOR DE POSICIONAMIENTO Y FACILITADOR. Ayuda a completar un perfil de empresa, pero no hagas pasar supuestos por hechos. Usa los datos actuales:\n${JSON.stringify(data.company||{},null,2)}\n\nEntrega estas secciones: A) resumen de lo que entendiste; B) propuesta de valor: 3 versiones provisionales con estructura “Ayudamos a [audiencia] a [necesidad/resultado] mediante [oferta/mecanismo]”, marcando campos inciertos; C) diferenciadores posibles: solo hipótesis y qué evidencia concreta haría falta para comprobar cada uno; D) 2-3 segmentos de audiencia candidatos, con necesidades/problemas y señales que permitirían confirmarlos; E) misión y tono sugeridos si ayudan; F) máximo 7 preguntas prioritarias, fáciles de responder, que más cambiarían la estrategia; G) mapa de qué texto podría copiarse a cada campo y qué debe quedar [POR VALIDAR]. No escribas afirmaciones falsas como si fueran verdaderas.` , 1500));
  $("#coach-strategy")?.addEventListener("click", () => run("#coach-strategy","#coach-strategy-status","#coach-strategy-result", data => `${rules}\n\nACTÚA COMO ESTRATEGA DE CONTENIDOS Y DOCENTE PARA PRINCIPIANTES. Perfil disponible:\n${JSON.stringify(data.company||{},null,2)}\nEstrategia actual:\n${JSON.stringify(data.strategy||{},null,2)}\n\nDiseña una propuesta inicial, no definitiva. Incluye: 1) qué hechos del perfil estás usando y qué datos faltan; 2) recomienda UNA prioridad de negocio y explica por qué; 3) redacta un objetivo de comunicación concreto; 4) recomienda 1 KPI principal y 2 secundarios, explica cómo se miden y qué línea base se necesita, sin inventar metas numéricas; 5) propone 3-5 pilares de comunicación adaptados a la oferta, cada uno con nombre, función, ejemplos de temas y porcentaje entero, sumando exactamente 100%; 6) recomienda hasta 2 redes prioritarias y, para cada una, explica el encaje hipotético, recursos necesarios y qué dato validaría la elección; no te bases solo en popularidad; 7) plantea un experimento de 30 días para aprender y criterios para continuar/cambiar; 8) señala las decisiones que el usuario debe confirmar. Si el perfil es insuficiente, ofrece opciones provisionales y empieza por las preguntas de mayor impacto. No digas que ya guardaste la estrategia.` , 1700));
  window.AppAssistant = { run };
})();
