/* Fase 8: planificación editorial local. No publica ni agenda en plataformas externas. */
(() => {
  "use strict";
  const $ = (selector, root=document) => root.querySelector(selector);
  const STATUS = { planned:"Planificado", "pending-human-review":"Pendiente de revisión", approved:"Aprobado", published:"Publicado manualmente", cancelled:"Cancelado" };
  const FORMATS = { post:"Publicación", carousel:"Carrusel", reel:"Reel / video", story:"Historias", poll:"Encuesta", ideas:"Lluvia de ideas", long_script:"Guion largo", designer_brief:"Brief para diseñador", product_copy:"Copy de producto/servicio" };
  const today = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
  const monthNow = () => today().slice(0,7);
  async function readData() { const state=await window.AppStorage.read(); if(state.warning) throw new Error(state.warning); return state.data || {}; }
  async function saveItems(items) { const data=await readData(); data.editorialPlan=items; const saved=await window.AppStorage.write(data); if(!saved.ok) throw new Error(saved.error || "No se pudo guardar el calendario."); window.dispatchEvent(new CustomEvent("content-commander:dashboard-updated")); }
  const make = (tag, cls, text) => { const el=document.createElement(tag); if(cls) el.className=cls; if(text !== undefined) el.textContent=text; return el; };
  function fillPillars(strategy) { const select=$("#cal-pillar"); if(!select) return; const value=select.value; select.replaceChildren(new Option("Sin pilar / por definir", "")); (strategy.pillars || []).forEach(p=>select.add(new Option(`${p.name} (${p.percentage}%)`,p.name))); if(Array.from(select.options).some(o=>o.value===value)) select.value=value; }
  function fillDrafts(drafts) { const select=$("#cal-draft"); if(!select) return; const value=select.value; select.replaceChildren(new Option("Sin borrador vinculado", "")); drafts.filter(d=>d.status==="approved" || d.approved===true).forEach(d=>select.add(new Option(`${d.typeLabel || FORMATS[d.type] || d.type} · ${d.network || "Red por definir"} · ${String(d.text||"").slice(0,55)}`,d.id))); if(Array.from(select.options).some(o=>o.value===value)) select.value=value; }
  function filtered(items) { const month=$("#calendar-month").value || monthNow(), status=$("#calendar-status-filter").value || "all"; return items.filter(item=>item.date?.startsWith(month) && (status==="all" || item.status===status)).sort((a,b)=>(a.date+(a.time||"00:00")).localeCompare(b.date+(b.time||"00:00"))); }
  function renderDistribution(items, strategy) {
    const root=$("#pillar-distribution"); root.replaceChildren(); const pillars=Array.isArray(strategy.pillars)?strategy.pillars:[];
    if(!pillars.length){root.append(make("p","helper","Define y guarda tus pilares en Estrategia para comparar la distribución planificada con los porcentajes deseados."));return;}
    const month=$("#calendar-month").value || monthNow(); const planned=items.filter(i=>i.date?.startsWith(month)&&i.status!=="cancelled"); const denominator=planned.length;
    const heading=make("h4","","Distribución por pilares · piezas del mes"); root.append(heading);
    pillars.forEach(p=>{const count=planned.filter(i=>i.pillar===p.name).length; const actual=denominator?count/denominator*100:0; const row=make("div","pillar-row"); const label=make("div","pillar-label"); label.append(make("b","",p.name),make("span","",`${count} piezas · objetivo ${Number(p.percentage)||0}% · actual ${actual.toFixed(0)}%`)); const track=make("div","pillar-track"); const bar=make("span","",""); bar.style.width=`${Math.min(100,actual)}%`; track.append(bar); row.append(label,track); root.append(row);});
    root.append(make("p","helper","Es una guía de distribución, no una cuota automática ni una predicción de resultados. Las piezas sin pilar también cuentan en el total mensual."));
  }
  function render(items, strategy, drafts) {
    const root=$("#calendar-items"); root.replaceChildren(); const rows=filtered(items); const allMonth=items.filter(i=>i.date?.startsWith($("#calendar-month").value||monthNow())&&i.status!=="cancelled");
    $("#calendar-summary").textContent=`${allMonth.length} piezas activas este mes · ${allMonth.filter(i=>i.status==="published").length} marcadas como publicadas manualmente · ${allMonth.filter(i=>i.status==="approved").length} aprobadas`;
    renderDistribution(items,strategy);
    if(!rows.length){root.append(make("p","helper","No hay piezas que coincidan con este mes y estado. Cambia el filtro o añade una publicación."));return;}
    rows.forEach(item=>{const card=make("article","calendar-item");const top=make("div","calendar-item-top");const title=make("h4","",item.title);const date=make("div","calendar-date",`${item.date}${item.time?` · ${item.time}`:""}`);top.append(title,date);const meta=make("p","calendar-meta",[item.network,FORMATS[item.format]||item.format,item.pillar||"Pilar por definir",item.goal,item.owner?`Responsable: ${item.owner}`:""].filter(Boolean).join(" · "));card.append(top,meta);
      if(item.notes) card.append(make("p","calendar-notes",item.notes));
      if(item.draftId){const draft=drafts.find(d=>d.id===item.draftId);card.append(make("p","helper",draft?`Borrador vinculado: ${draft.typeLabel||FORMATS[draft.type]||draft.type} · ${draft.status==="approved"||draft.approved?"aprobado (no publicado)":"su estado cambió; revisar antes de usar"}`:"El borrador vinculado ya no está disponible."));}
      const actions=make("div","calendar-item-actions");const statusLabel=make("label","calendar-status-label","Estado");const select=make("select","calendar-status");Object.entries(STATUS).forEach(([value,label])=>select.add(new Option(label,value)));select.value=STATUS[item.status]?item.status:"planned";select.setAttribute("aria-label",`Estado de ${item.title}`);statusLabel.append(select);select.addEventListener("change",async()=>{if(select.value==="published"&&!confirm("¿Confirmas que esta pieza ya se publicó fuera de la app? La aplicación no publica contenido.")){select.value=item.status;return;}if(select.value==="published"&&!item.publishedAt)item.publishedAt=new Date().toISOString();if(select.value!=="published")delete item.publishedAt;item.status=select.value;item.statusUpdatedAt=new Date().toISOString();try{await saveItems(items);message("Estado guardado.");render(items,strategy,drafts);}catch(e){message(e.message,true);}});
      const remove=make("button","button button-secondary calendar-remove","Eliminar");remove.type="button";remove.addEventListener("click",async()=>{if(!confirm(`¿Eliminar “${item.title}” del calendario?`))return;try{await saveItems(items.filter(x=>x.id!==item.id));message("Pieza eliminada del calendario.");await refresh();}catch(e){message(e.message,true);}});actions.append(statusLabel,remove);card.append(actions);root.append(card);});
  }
  function message(text,error=false){const el=$("#calendar-feedback");if(el){el.textContent=text;el.dataset.state=error?"error":"success";}}
  async function refresh(){const data=await readData();const items=Array.isArray(data.editorialPlan)?data.editorialPlan:[];fillPillars(data.strategy||{});const drafts=Array.isArray(data.contentDrafts)?data.contentDrafts:[];fillDrafts(drafts);render(items,data.strategy||{},drafts);}
  function init(){const form=$("#calendar-form");if(!form)return;$("#cal-date").min=today();$("#calendar-month").value=monthNow();$("#calendar-month").addEventListener("change",()=>refresh().catch(e=>message(e.message,true)));$("#calendar-status-filter").addEventListener("change",()=>refresh().catch(e=>message(e.message,true)));
    form.addEventListener("submit",async event=>{event.preventDefault();const title=$("#cal-title").value.trim(),date=$("#cal-date").value,network=$("#cal-network").value,format=$("#cal-format").value;if(!title||!date||!network||!format){message("Completa título, fecha, red y formato.",true);return;}if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(Date.parse(date+"T12:00:00"))){message("La fecha no es válida.",true);return;}try{const data=await readData();const items=Array.isArray(data.editorialPlan)?data.editorialPlan.slice():[];const drafts=Array.isArray(data.contentDrafts)?data.contentDrafts:[];const draftId=$("#cal-draft").value;const linked=drafts.find(d=>d.id===draftId);if(draftId&&(!linked||!(linked.status==="approved"||linked.approved===true))){message("Solo puedes vincular borradores aprobados. Revisa el borrador seleccionado.",true);return;}const item={id:crypto.randomUUID?crypto.randomUUID():`calendar-${Date.now()}-${Math.random().toString(16).slice(2)}`,title,date,time:$("#cal-time").value,network,format,pillar:$("#cal-pillar").value,goal:$("#cal-goal").value,owner:$("#cal-owner").value.trim(),draftId:draftId||"",notes:$("#cal-notes").value.trim(),status:"planned",createdAt:new Date().toISOString(),statusUpdatedAt:new Date().toISOString()};items.push(item);await saveItems(items);form.reset();$("#cal-date").min=today();$("#calendar-month").value=date.slice(0,7);message("Pieza añadida al calendario como Planificada. No se ha publicado.");await refresh();}catch(e){message(e.message||"No se pudo guardar la publicación.",true);}});
    window.addEventListener("content-commander:strategy-updated",()=>refresh().catch(e=>message(e.message,true)));window.addEventListener("content-commander:drafts-updated",()=>refresh().catch(e=>message(e.message,true)));refresh().catch(e=>message(e.message||"No se pudo cargar el calendario.",true));
  }
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
  window.AppCalendar={refresh,constants:{STATUS,FORMATS}};
})();
