/* Fase 10: investigación asistida con trazabilidad; sin rastreo web automático. */
(() => {
  "use strict";
  const $ = (s, r=document) => r.querySelector(s);
  let activeResearch = null;
  let latestReport = "";
  const nowDate = () => new Date().toISOString().slice(0,10);
  const escUrl = value => { try { const u=new URL(value); return ["http:","https:"].includes(u.protocol) ? u.href : ""; } catch (_) { return ""; } };
  async function stateData(){ const s=await window.AppStorage.read(); if(s.warning) throw new Error(s.warning); return s.data||{}; }
  async function saveData(data){ const r=await window.AppStorage.write(data); if(!r.ok) throw new Error(r.error||"No se pudo guardar."); }
  function makeEl(tag, cls, text){ const el=document.createElement(tag); if(cls) el.className=cls; if(text!==undefined) el.textContent=text; return el; }
  async function refreshPillars(){
    const data=await stateData().catch(()=>({})); const pillars=data.strategy?.pillars||[];
    const select=$("#research-pillar"); if(!select)return; const selected=select.value;
    select.replaceChildren(new Option("Sin pilar específico",""));
    pillars.forEach(p=>select.add(new Option(`${p.name}${p.percentage!=null?` (${p.percentage}%)`:""}`,p.name)));
    if(pillars.some(p=>p.name===selected))select.value=selected;
  }
  function renderSources(){
    const wrap=$("#research-sources"); if(!wrap)return; wrap.replaceChildren();
    const sources=activeResearch?.sources||[];
    if(!sources.length){wrap.append(makeEl("p","helper","Aún no hay fuentes registradas para esta investigación."));return;}
    sources.forEach((src,i)=>{const card=makeEl("article","research-source");const h=makeEl("h4","",src.title);const url=escUrl(src.url);if(url){const a=makeEl("a","text-button","Abrir fuente ↗");a.href=url;a.target="_blank";a.rel="noopener noreferrer";card.append(h,a);}else card.append(h);card.append(makeEl("p","research-source-meta",`Fecha: ${src.date||"no indicada"} · Registrada: ${new Date(src.savedAt).toLocaleDateString("es-MX")}`));card.append(makeEl("p","research-source-notes",src.notes));const del=makeEl("button","button button-secondary research-delete","Eliminar fuente");del.type="button";del.addEventListener("click",()=>{activeResearch.sources.splice(i,1);renderSources();renderLibrary();});card.append(del);wrap.append(card);});
  }
  function renderReport(){const node=$("#research-analysis-result");node.replaceChildren();if(!latestReport){node.append(makeEl("p","helper","La síntesis distinguirá hallazgos documentados, interpretaciones, hipótesis y datos que faltan."));return;}node.append(makeEl("pre","research-report",latestReport));$("#save-research-report").disabled=false;}
  async function renderLibrary(){
    const wrap=$("#research-library");if(!wrap)return;wrap.replaceChildren();let data;try{data=await stateData()}catch(e){wrap.append(makeEl("p","helper",e.message));return;}
    const list=Array.isArray(data.researchLibrary)?data.researchLibrary:[];
    if(!list.length){wrap.append(makeEl("p","helper","Todavía no hay investigaciones guardadas."));return;}
    list.slice().sort((a,b)=>(b.updatedAt||b.createdAt||"").localeCompare(a.updatedAt||a.createdAt||"")).forEach(item=>{const card=makeEl("article","research-library-item");card.append(makeEl("h4","",item.topic));card.append(makeEl("p","research-source-meta",`${item.sources?.length||0} fuente(s) · ${item.pillar||"Sin pilar"} · ${item.updatedAt?new Date(item.updatedAt).toLocaleDateString("es-MX"):""}`));if(item.report)card.append(makeEl("p","research-library-summary",item.report.slice(0,380)+(item.report.length>380?"…":"")));const actions=makeEl("div","research-library-actions");const open=makeEl("button","button button-secondary","Abrir investigación");open.type="button";open.addEventListener("click",()=>{activeResearch=structuredClone(item);latestReport=item.report||"";$("#research-topic").value=item.topic||"";$("#research-audience").value=item.audience||"";$("#research-goal").value=item.goal||"Educar";$("#research-pillar").value=item.pillar||"";renderSources();renderReport();$("#research-analysis-feedback").textContent="Investigación cargada. Revisa la fecha de las fuentes antes de reutilizarla.";});actions.append(open);const del=makeEl("button","button button-secondary","Eliminar");del.type="button";del.addEventListener("click",async()=>{if(!confirm("¿Eliminar esta investigación guardada?"))return;const d=await stateData();d.researchLibrary=(d.researchLibrary||[]).filter(x=>x.id!==item.id);await saveData(d);renderLibrary();});actions.append(del);card.append(actions);wrap.append(card);});
  }
  function createResearch(){return {id:crypto.randomUUID?crypto.randomUUID():`research-${Date.now()}`,topic:$("#research-topic").value.trim(),audience:$("#research-audience").value.trim(),goal:$("#research-goal").value,pillar:$("#research-pillar").value,sources:[],report:"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};}
  function ensureActive(){if(!activeResearch||activeResearch.topic!==$("#research-topic").value.trim()){activeResearch=createResearch();latestReport="";}activeResearch.audience=$("#research-audience").value.trim();activeResearch.goal=$("#research-goal").value;activeResearch.pillar=$("#research-pillar").value;return activeResearch;}
  function init(){
    $("#research-source-date").value=nowDate();
    $("#research-form").addEventListener("submit",e=>{e.preventDefault();activeResearch=ensureActive();const topic=activeResearch.topic;const links=$("#research-search-links");links.replaceChildren();links.hidden=false;links.append(makeEl("p","helper","Busca fuentes recientes y confiables; las páginas no se han leído automáticamente por esta app."));[["Google",`https://www.google.com/search?q=${encodeURIComponent(topic)}`],["Google News",`https://news.google.com/search?q=${encodeURIComponent(topic)}`],["Bing",`https://www.bing.com/search?q=${encodeURIComponent(topic)}`]].forEach(([label,url])=>{const a=makeEl("a","button button-secondary",`${label} ↗`);a.href=url;a.target="_blank";a.rel="noopener noreferrer";links.append(a);});$("#research-feedback").textContent="Búsquedas preparadas. Revisa los resultados, elige fuentes y registra sus hallazgos abajo.";});
    $("#research-source-form").addEventListener("submit",e=>{e.preventDefault();try{const url=escUrl($("#research-source-url").value.trim());if(!url)throw new Error("Introduce una URL http o https válida.");activeResearch=ensureActive();activeResearch.sources.push({title:$("#research-source-title").value.trim(),url,date:$("#research-source-date").value,notes:$("#research-source-notes").value.trim(),savedAt:new Date().toISOString()});activeResearch.updatedAt=new Date().toISOString();$("#research-source-form").reset();$("#research-source-date").value=nowDate();renderSources();$("#research-feedback").textContent="Fuente añadida a esta investigación. Guarda la investigación para conservarla después de cerrar la página.";$("#research-feedback").dataset.state="success";}catch(err){$("#research-feedback").textContent=err.message;$("#research-feedback").dataset.state="error";}});
    $("#analyze-research").addEventListener("click",async()=>{const btn=$("#analyze-research");try{activeResearch=ensureActive();if(!activeResearch.sources.length)throw new Error("Registra al menos una fuente y su hallazgo antes de sintetizar.");if(!window.AppCohere)throw new Error("No se encontró el módulo Cohere.");btn.disabled=true;btn.textContent="Analizando…";$("#research-analysis-feedback").textContent="Solicitando síntesis a Cohere. Esto no verifica de forma independiente las fuentes.";const sourceText=activeResearch.sources.map((s,i)=>`FUENTE ${i+1}\nTítulo: ${s.title}\nURL: ${s.url}\nFecha indicada: ${s.date||"no indicada"}\nNotas aportadas por la persona usuaria: ${s.notes}`).join("\n\n");const prompt=`Actúa como asistente de investigación editorial. Analiza SOLO los datos y notas proporcionados abajo. No afirmes haber abierto, leído ni verificado las URL. No inventes cifras, fechas, consenso, popularidad ni tendencias. Separa claramente: (1) hallazgos que aparecen en las notas proporcionadas, (2) interpretación posible, (3) hipótesis para contenido que requiere validación, (4) información faltante/limitaciones, (5) 5 ángulos de contenido alineados con objetivo y pilar, con formatos sugeridos y pregunta de validación para cada uno, (6) fuentes que convendría contrastar. Si las notas no respaldan una tendencia, dilo claramente. No confundas presencia en una fuente con prevalencia en toda la audiencia.\nPREGUNTA: ${activeResearch.topic}\nAUDIENCIA: ${activeResearch.audience||"No especificada"}\nOBJETIVO: ${activeResearch.goal}\nPILAR: ${activeResearch.pillar||"Sin pilar"}\nNOTAS DE FUENTES (aportadas manualmente, no verificadas por la IA):\n${sourceText}`;const result=await window.AppCohere.chat([{role:"user",content:prompt}],{maxTokens:1700,temperature:0.2});latestReport=result.text;activeResearch.report=latestReport;activeResearch.model=result.model;activeResearch.updatedAt=new Date().toISOString();renderReport();$("#research-analysis-feedback").textContent="Síntesis generada. Comprueba cada interpretación contra las fuentes originales antes de convertirla en contenido.";$("#research-analysis-feedback").dataset.state="success";}catch(err){$("#research-analysis-feedback").textContent=err.message||"No se pudo analizar la investigación.";$("#research-analysis-feedback").dataset.state="error";}finally{btn.disabled=false;btn.textContent="Analizar evidencia con Cohere";}});
    $("#save-research-report").addEventListener("click",async()=>{try{activeResearch=ensureActive();activeResearch.report=latestReport;activeResearch.updatedAt=new Date().toISOString();const d=await stateData();d.researchLibrary=Array.isArray(d.researchLibrary)?d.researchLibrary:[];const index=d.researchLibrary.findIndex(x=>x.id===activeResearch.id);if(index>=0)d.researchLibrary[index]=structuredClone(activeResearch);else d.researchLibrary.push(structuredClone(activeResearch));await saveData(d);$("#research-analysis-feedback").textContent="Investigación y síntesis guardadas en IndexedDB. Se incluirán en el siguiente respaldo JSON.";$("#research-analysis-feedback").dataset.state="success";await renderLibrary();}catch(err){$("#research-analysis-feedback").textContent=err.message;$("#research-analysis-feedback").dataset.state="error";}});
    window.addEventListener("content-commander:route-changed",e=>{if(e.detail?.view==="investigacion"){refreshPillars();renderLibrary();}});window.addEventListener("content-commander:strategy-updated",refreshPillars);window.AppResearch={refresh:renderLibrary};refreshPillars();renderLibrary();
  }
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
